name: Deploy Shiny App to shinyapps.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.1'
    - name: Install dependencies
      run: |
        Rscript -e "install.packages('remotes', repos='http://cran.rstudio.com/')"
        Rscript -e "remotes::install_cran('shiny')"
        Rscript -e "remotes::install_cran('rsconnect')"
    - name: Check rsconnect installation
      run: |
        Rscript -e "if (!require(rsconnect)) stop('Package not installed', call. = FALSE)"
    - name: Deploy to shinyapps.io
      env:
        SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
        SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
        SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
      run: |
        Rscript -e "rsconnect::setAccountInfo(name=Sys.getenv('SHINYAPPS_ACCOUNT'), token=Sys.getenv('SHINYAPPS_TOKEN'), secret=Sys.getenv('SHINYAPPS_SECRET'))"
        Rscript -e "rsconnect::deployApp(appName='consultingproject')"
